### PR TITLE
MQFLAG device

### PR DESCRIPTION
**Pull request by sejgit**
This one may or may not fit where you want this Poly to go as this is not a device but a conduit for the IOT processor to signal the ISY with a condition through MQTT creating a device which your ISY program can trigger from.  As you can surmise I am not using a regular SONOFF device program but my own program.

From the program comments:
This is meant as a flag for if you have a sensor or condition on your IOT device which you want the device program rather than the ISY to flag as OK, NOK, LO, HI, ERR(OR).
Payload is direct (like SW) not JSON encoded (like SENSOR)
# example device: liquid float {OK, LO, HI}, temp {OK, NOK, LO, HI, ERR}
# example condition: IOT devices sensor connections {OK, NOK, ERR(OR)}

I am using this in a fishtank application for float(water level) & temperature, as well as connection of the IOT to its devices (OK, ERR) condition.

It has a reset button command which would go out over the CMD topic.  I use to reset the condition.

Hope its useful to someone.

### CODE REVIEW

**Comment by exking** [comment]
can you add `POLYGLOT_CONFIG.md` entry please?

**Comment by sejgit** [comment]
Now that was not very smart of my…..of course!

**Comment by sejgit** [comment]
Done & tested.

**Comment by whittedb** [comment]
Now this sounds really useful.  I've been using Tasmota rules and bastardizing the switch "type" funtionallity to do this, but the flag "type" will allow me to reduce the complexity of my rules.  Thank you!

**Comment by sejgit** [comment]
Very welcome!
Also between this and the MQTemp were my first pulls. So thanks to this repo for getting me to finally learn that work flow. 

Stephen

**Pull request merged**
